module.exports = {
    SUCCESS: {
      USER_CREATED: "USER_CREATED",
      USER_FETCHED: "USER_FETCHED",
      USERS_FETCHED: "USERS_FETCHED",
      USER_UPDATED: "USER_UPDATED",
      USER_DELETED: "USER_DELETED",
    },
    ERROR: {
      USER_NOT_FOUND: "USER_NOT_FOUND",
      EMAIL_EXISTS: "EMAIL_EXISTS",
      CREATE_FAILED: "CREATE_FAILED",
      FETCH_FAILED: "FETCH_FAILED",
      UPDATE_FAILED: "UPDATE_FAILED",
      DELETE_FAILED: "DELETE_FAILED",
      LOGIN_FAILED: "LOGIN_FAILED",
      NO_TOKEN: "NO_TOKEN",
      INVALID_TOKEN: "INVALID_TOKEN",
      ACCESS_DENIED: "ACCESS_DENIED",
      USER_NOT_AUTHENTICATED: "USER_NOT_AUTHENTICATED",
    }
  };
  